name: my_app
description: Tracking App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ">=0.16.1 <1.0.0"
  # StateManagement
  hooks_riverpod: ">=0.12.0 <1.0.0"
  flutter_hooks: ">=0.14.0 <1.0.0"
  freezed_annotation: ">=0.11.0 <1.0.0"
  state_notifier: ">=0.6.0 <1.0.0"
  # Firebase
  firebase_core:  ">=0.5.3 <1.0.0"
  cloud_firestore: ">=0.14.4 <1.0.0"
  firebase_auth: ">=0.18.4 <1.0.0"
  # Sign-in
  flutter_signin_button: ">=1.1.0 <2.0.0"
  google_sign_in: ">=4.5.6 <5.0.0"
  # Other
  adaptive_dialog: ">=0.9.3 <1.0.0"
  device_preview: ">=0.5.5 <1.0.0"
  gap: ">=1.2.0 <2.0.0"
  simple_logger: ">=1.7.0 <2.0.0"
  auto_size_text: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true